### ISSUE TITLE
invalid checksum is possible if bytes are written separately

### ISSUE THREAD

**Issue by DonBrinn** [archiverjs/node-crc32-stream#27]
There is [a defect](https://github.com/alexgorbatchev/node-crc/issues/66) in the crc module used.

Because of that underlying defect, writing the same list of bytes to crc32-stream can result in a different checksum value depending on how the list of bytes is split across different stream.write() calls.

Consider the following:
```
    const checksum = new CRC32Stream();
    const deadend = new DeadEndStream();
    
    checksum.on('end', function() {
      console.log(checksum.digest().readUInt32BE(0);
      done();
    });
    
    checksum.write(Buffer.from([157, 10, 217, 109]));
    checksum.write(Buffer.from([100, 200, 300]));
    checksum.end();
    checksum.pipe(deadend);
```
and
```
    const checksum = new CRC32Stream();
    const deadend = new DeadEndStream();
    
    checksum.on('end', function() {
      console.log(checksum.digest().readUInt32BE(0);
      done();
    });
    
    checksum.write(Buffer.from([157, 10, 217, 109, 100, 200, 300]));
    checksum.end();
    checksum.pipe(deadend);
```

Those should result in the same checksum value, but the first snippet results in a checksum value of `2178592166` (which is incorrect) and the second snippet results in a checksum value of `2170850123` (which is correct).

Suggested fix:  Switch to using the `crc-32` module instead.

**Comment by alexgorbatchev** [comment]
Hi @DonBrinn, I believe this is the expected behavior. The default initial value for CRC32 is `0xFFFFFFFF`, which is `-1`. This could be verified over at http://www.sunshine2k.de/coding/javascript/crc/crc_js.html for example. CRC32 of `helloworld` is `0xF9EB20AD` with __default__ CRC32 `Initial Value` of `0xFFFFFFFF`. Changing initial value to `0` produces `0xE59EB724`.

I've also verified this with Ruby:

```rb
require 'zlib'

puts("no initial value   : #{(Zlib::crc32('helloworld')).to_s(16)}")
puts("with initial value : #{Zlib::crc32('world', Zlib::crc32('hello')).to_s(16)}")
>
no initial value   : f9eb20ad
with initial value : f9eb20ad
```

The same output is produced by `node-crc` CRC32 function:

```js
const together = crc32(Buffer.from('helloworld'));
let separately = crc32(Buffer.from('hello'));
separately = crc32(Buffer.from('world'), separately);
expect(separately).to.equal(together);

console.log({
  crc: crc32.model,
  together: together.toString(16),
  separately: separately.toString(16),
});
>
{ crc: 'crc-32', together: 'f9eb20ad', separately: 'f9eb20ad' }
```
