### ISSUE TITLE
Crash on Node.js v8.0.0

### ISSUE THREAD

**Issue by iarna** [archiverjs/node-crc32-stream#5]
There seems to be a Node.js bug that makes `zlib.deflateRaw` only extensible using the `class` keyword. Using traditional methods as in [deflate-crc32-stream.js](https://github.com/archiverjs/node-crc32-stream/blob/master/lib/deflate-crc32-stream.js) results in the constructor not being called and any attempt to use the resulting stream to crash.

This is mostly an FYI, as I hope it'll be fixed on the Node.js side. It was reported here: https://github.com/nodejs/node/issues/13358

**Comment by ctalkington** [comment]
looks like node addressed this one.
