### ISSUE TITLE
the content is not read

### ISSUE THREAD

**Issue by beenotung** [archiverjs/node-crc32-stream#9]
I tried both methods of pipe and write manually on each 'data' event, but I get no output.
The process stop immediately indeed.

Not working example:
```typescript
let fs = require('fs');
let CRC32Stream = require('crc32-stream');

export async function crcFile2(path: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    let source = fs.createReadStream(path);
    let checksum = new CRC32Stream();

    checksum.on('end', function (err) {
      err ? reject(err) : resolve(checksum.digest())
      // do something with checksum.digest() here
    });

    source.pipe(checksum);
  });
}
```

Working example using another library:
```typescript
let fs = require('fs');
let crc32 = require('buffer-crc32');

export async function crcFile(path: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    let acc = crc32('');
    fs.createReadStream(path)
      .on('data', buffer => acc = crc32(buffer, acc))
      .on('end', () => resolve(acc))
      .on('error', e => reject(e))
  });
}
```

**Comment by Jimbly** [comment]
I'm also unable to get this library to work, the end event never fires, though the source stream seems consumed (process exits).  Tried using Node versions 6, 8, 10, and 11, in case it was related to stream API changes or something.  Switching to `buffer-crc32` or `crc-32` and doing streaming myself seems to work.

**Comment by ctalkington** [comment]
have you tried listening for `error`? this module is used in compress-commons and I have seen any issues. You'll have to forgive me as I'm not fully up to speed on ES6 syntax to follow your example

**Comment by kyle-johnson** [comment]
You need to [change the stream mode](https://nodejs.org/api/stream.html#stream_two_reading_modes):

```js
source.pipe(checksum);
checksum.resume();
```
